services:
  - type: web
    name: jaredluyster-com
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd marketplace && gunicorn server:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.11"
